
[functions.geocode-ma-courses]
enabled = true
verify_jwt = true
import_map = "./functions/geocode-ma-courses/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/geocode-ma-courses/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/geocode-ma-courses/*.html" ]

[functions.geocode-existing-courses]
enabled = true
verify_jwt = true
import_map = "./functions/geocode-existing-courses/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/geocode-existing-courses/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/geocode-existing-courses/*.html" ]
